### ISSUE TITLE
ReadME images are missing

### ISSUE THREAD

**Issue by nitansh11** [sujeetcoder/friendly-stage-2043#82]
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/8274883/212072134-a794f1df-28bc-44e1-b07f-295f74f61f0e.png">

Please write a detailed read me file which should include all functionalities of your app.

**Comment by nitansh11** [comment]
Avoid use of "me" in team projects:
<img width="965" alt="image" src="https://user-images.githubusercontent.com/8274883/212072799-d574e989-7cc4-4527-b6f6-a4955b5238c7.png">

**Comment by Nilesh2697** [comment]
- [ ] done
